[package]
name = "nalgebra-mlp"
version = "0.1.0"
edition = "2024"

[dependencies]
approx = "0.5.1"
nalgebra = "0.33.2"
paste = "1.0.15"
rand = "0.9.1"

[dev-dependencies]
mnist = { version="0.6", features=["download"]}
